server:
  port: 8080

# h2 관리자 콘솔 활성화
spring:
  h2:
    console:
      enabled: true

      spring:
  datasource:
    url: jdbc:h2:mem:testdb   # 고정된 값으로 접속이 가능
    driver-class-name: org.h2.Driver
    username: sa
    password: