

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  #schema.sql 과 data.sql 관리 가능 ( always|never )
  sql:
    init:
      mode: always

# TodoMapper.xml 과  DTO 별칭 설정
mybatis:
  mapper-locations: com/exam/config/TodoMapper.xml
  type-aliases-package: com.exam.dto