


# MySQL DB 연동
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

# schema.sql 과 data.sql 관리
  sql:
    init:
      mode: never  # never
